const assert=require('node:assert/strict');
const {nextAction}=require('./assets/dds-coach.js');
const s={exercise_mode:'actions',status:'В работе',owner_service:'Служба 104',events:[],service_states:{},crew_options:[{id:'17'}]};
assert.equal(nextAction(s).target,'responseStatus');
s.service_states['Служба 104']={status:'Получена службой'};
assert.equal(nextAction(s).target,'responseStatus');
s.service_states['Служба 104']={status:'Принята'};
assert.equal(nextAction(s).target,'crewSelect');s.assigned_crew={id:'17'};
assert.equal(nextAction(s).target,'openBriefing');
s.events.push({seq:1,type:'notification.recorded',detail:{source:'briefing',counterpart:'crew',crew_id:'17'}});
assert.equal(nextAction(s).target,'openBriefing');assert.match(nextAction(s).title,/вышестоящему/);
s.events.push({seq:1,type:'notification.recorded',detail:{source:'briefing',counterpart:'superior'}});
assert.equal(nextAction(s).target,'requestProgress');
s.pending_phone_reports=[{id:'arrived'}];assert.equal(nextAction(s).target,'situationFeed');
s.events.push({seq:2,type:'situation.update',detail:{text:'Бригада прибыла.',unlocks_status:'Прибытие'}});
assert.equal(nextAction(s).target,'responseComment');
s.events.push({seq:3,type:'service.updated',detail:{service:'Служба 104',status:'Прибытие'}});
s.pending_phone_reports=[];assert.equal(nextAction(s).target,'requestProgress');
s.card_locked=true;assert.equal(nextAction(s).target,'processed');
s.processed_at='now';assert.equal(nextAction(s).target,'finish');
s.status='Завершена';assert.equal(nextAction(s).target,'audit');
assert.equal(nextAction({...s,exercise_mode:'fill'}),null);
console.log('DDS coach: real-action progression passed');
