// Headless role-aware regression with intercepted HTTP; no credentials or database.
const playwright=require('playwright/test'),{expect}=playwright;
// Движок выбирается BROWSER_ENGINE: chromium покрывает Chrome и Яндекс.Браузер,
// firefox — второй движок из требований к совместимости.
const engine=playwright[process.env.BROWSER_ENGINE||'chromium'];
if(!engine)throw Error('Unknown BROWSER_ENGINE '+process.env.BROWSER_ENGINE);
const fs=require('node:fs/promises'),path=require('node:path');
const root=__dirname,origin='http://127.0.0.1:3000',sid='11111111-1111-4111-8111-111111111111';
let policy={revision:0,policy:null},expert={revision:0,current:null,history:[]},role='teacher',policyConflictOnce=true,expertFailureOnce=true,expertConflictOnce=true,lastExpertRequest='',insightsGenerated=false;
const calls=[];
const summary={attempts:1,completed:1,graded:1,passed:0,failed:1,unassessed:0,average_score:0,average_seconds:42};
function assessment(){return {session_id:sid,automatic:{status:'graded',score_percent:0,criteria:[{id:'street',label:'Улица',field:'street',expected:['Учебная улица'],actual:'Другая улица',passed:false}]},policy_result:{passed:false,field_errors:1,sequence_errors:1,checks:[{id:'score',passed:false,actual:0,limit:60}],steps:[{id:'save',label:'Сохранить',event_type:'card.saved',passed:true,reason:'',event_seq:2},{id:'finish',label:'Завершить',event_type:'session.finished',passed:false,reason:'Нарушен порядок',event_seq:1}],policy_revision:1},expert,effective:expert.current?.action==='grade'?{score_percent:expert.current.score_percent,passed:expert.current.passed,source:'expert'}:{score_percent:0,passed:false,source:'automatic'}};}
function statistics(){return {summary,progress:[{session_id:sid,title:'Учебное задымление',finished_at:new Date().toISOString(),score_percent:expert.current?.action==='grade'?expert.current.score_percent:0,passed:expert.current?.action==='grade'?expert.current.passed:false,source:expert.current?.action==='grade'?'expert':'automatic',difficulty:'basic',dds_profile:'fire'}],students:role==='teacher'?[{student_id:'student-1',display_name:'Учебный студент',...summary}]:[],typical_errors:[{key:'field',label:'Ошибка заполнения',count:1,attempts:1,rate_percent:100}],by_scenario:[{scenario_id:'scenario-1',title:'Учебное задымление',...summary}]};}
async function serve(page){await page.route('**/*',async route=>{const request=route.request(),url=new URL(request.url()),p=url.pathname;if(url.origin!==origin)return route.abort();if(p.startsWith('/api/')){calls.push(`${role}:${request.method()}:${p}`);let data,status=200;
 if(p==='/api/v1/auth/me')data={id:role+'-1',display_name:role==='teacher'?'Преподаватель':'Студент',role};
 else if(p==='/api/scenarios')data=[{id:'scenario-1',title:'Учебное задымление'}];
 else if(p==='/api/v1/instructor/groups')data=[{id:'group-1',title:'Группа 1'}];
 else if(p==='/api/v1/instructor/sessions')data=[{id:sid,number:7,status:'Завершена',scenario_title:'Учебное задымление',student_name:'Учебный студент',finished_at:new Date().toISOString(),score_percent:0}];
 else if(p==='/api/v1/instructor/scenarios/scenario-1/assessment-policy'&&request.method()==='GET')data=policy;
 else if(p==='/api/v1/instructor/scenarios/scenario-1/assessment-policy'&&request.method()==='PUT'){const body=request.postDataJSON();if(policyConflictOnce){policyConflictOnce=false;return route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({detail:'Версия правил устарела'})});}if(body.revision!==policy.revision)throw Error('stale policy revision');policy={revision:policy.revision+1,policy:body.policy};data=policy;}
 else if(p==='/api/v1/instructor/statistics'||p==='/api/v1/student/statistics')data=statistics();
 else if(p==='/api/v1/instructor/groups/group-1/insights'&&request.method()==='GET')data=insightsGenerated?{version:'group-insights-v1',status:'mock',group_id:'group-1',created_at:new Date().toISOString(),provider:'mock',model:'scenario-mock',aggregate:{completed_attempts:4,current_group_size:2,participant_count:2},evidence:[{key:'error_1',kind:'field',scenario_id:'scenario-1',label:'Адрес',configuration_revision:1,error_count:3,eligible_attempts:4,rate_percent:75}],limitations:['Малая выборка'],summary:'Демонстрационная агрегированная сводка.',difficult_skills:[{label:'Сбор адреса',explanation:'Повторяющаяся ошибка.',evidence_key:'error_1'}],recommendations:[{title:'Повторить задымление',rationale:'Связано с ошибкой адреса.',scenario_ids:['scenario-1'],evidence_keys:['error_1']}],stale:true,stale_reasons:['Добавлены новые попытки.']}:{status:'not_generated',group_id:'group-1'};
 else if(p==='/api/v1/instructor/groups/group-1/insights'&&request.method()==='POST'){insightsGenerated=true;data={version:'group-insights-v1',status:'mock',group_id:'group-1',created_at:new Date().toISOString(),provider:'mock',model:'scenario-mock',aggregate:{completed_attempts:4,current_group_size:2,participant_count:2},evidence:[{key:'error_1',kind:'field',scenario_id:'scenario-1',label:'Адрес',configuration_revision:1,error_count:3,eligible_attempts:4,rate_percent:75}],limitations:['Малая выборка'],summary:'Демонстрационная агрегированная сводка.',difficult_skills:[{label:'Сбор адреса',explanation:'Повторяющаяся ошибка.',evidence_key:'error_1'}],recommendations:[{title:'Повторить задымление',rationale:'Связано с ошибкой адреса.',scenario_ids:['scenario-1'],evidence_keys:['error_1']}],stale:false,stale_reasons:[]};}
 else if(p===`/api/v1/${role==='teacher'?'instructor':'student'}/sessions/${sid}/assessment`&&request.method()==='GET')data=assessment();
 else if(p===`/api/v1/instructor/sessions/${sid}/assessment`&&request.method()==='POST'){const body=request.postDataJSON();if(body.action==='grade'&&expertFailureOnce){expertFailureOnce=false;lastExpertRequest=body.request_id;return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'Временная ошибка сохранения'})});}if(body.action==='grade'&&lastExpertRequest!==body.request_id)throw Error('Expert retry changed request_id');if(body.action==='revoke'&&expertConflictOnce){expertConflictOnce=false;lastExpertRequest=body.request_id;return route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({detail:'Версия решения устарела'})});}if(body.action==='revoke'&&lastExpertRequest!==body.request_id)throw Error('Expert conflict retry changed request_id');if(body.revision!==expert.revision)throw Error('stale expert revision');const review={revision:expert.revision+1,request_id:body.request_id,action:body.action,score_percent:body.score_percent,passed:body.passed,reason:body.reason,teacher_id:'teacher-1',teacher_name:'Преподаватель',at:new Date().toISOString()};expert={revision:review.revision,current:body.action==='grade'?review:null,history:[...expert.history,review]};data=assessment();}
 else throw Error(`Unexpected API ${request.method()} ${p}`);
 return route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});}
 const file=p==='/assessment'?'assessment.html':p.slice(1);if(file.includes('..'))throw Error('Unsafe asset');const body=await fs.readFile(path.join(root,file));return route.fulfill({body,contentType:file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html'});});}
(async()=>{const browser=await engine.launch({headless:true,...(process.env.LESSON_BROWSER_PATH?{executablePath:process.env.LESSON_BROWSER_PATH}:{})});try{
 const teacher=await browser.newPage({viewport:{width:1400,height:1000}}),errors=[];teacher.on('pageerror',e=>errors.push(e.message));teacher.on('dialog',d=>d.accept());await serve(teacher);await teacher.goto(origin+'/assessment');await expect(teacher.locator('#teacherPolicy')).toBeVisible();await expect(teacher.locator('#summary')).toContainText('0%');
 await teacher.locator('#policyEnabled').check();await teacher.locator('#passScore').fill('60');await teacher.locator('#fieldErrors').fill('2');await teacher.locator('#addStep').click();await teacher.locator('.step [data-key="label"]').fill('Сначала сохранить');await teacher.locator('.step [data-key="event_type"]').selectOption('card.saved');await teacher.locator('#savePolicy').click();await expect(teacher.locator('#status')).toContainText('уже изменены');await expect(teacher.locator('#passScore')).toHaveValue('60');await teacher.locator('#savePolicy').click();await expect(teacher.locator('#status')).toContainText('Правила сохранены');if(policy.policy.pass_score_percent!==60||policy.policy.steps.length!==1)throw Error('Policy form was not serialized');
 await teacher.locator('#groupFilter').selectOption('group-1');await expect(teacher.locator('#insightsState')).toContainText('ещё не формировались');await teacher.locator('#generateInsights').click();await expect(teacher.locator('#insightsResult')).toContainText('Адрес: 3 из 4 (75%)');await expect(teacher.locator('#insightsResult')).toContainText('Каталог сценариев (ID: scenario-1)');await expect(teacher.locator('#insightsResult a[href="/portal"]')).toBeVisible();
 await teacher.getByText('Оценить и открыть аудит').click();await expect(teacher.locator('#assessmentDialog')).toBeVisible();await expect(teacher.locator('#assessmentDetail')).toContainText('ожидалось «Учебная улица»');await teacher.locator('#expertScore').fill('85');await teacher.locator('#expertPassed').selectOption('true');await teacher.locator('#expertReason').fill('Проверено преподавателем');await teacher.locator('#grade').click();await expect(teacher.locator('#dialogStatus')).toContainText('Временная ошибка');await expect(teacher.locator('#expertReason')).toHaveValue('Проверено преподавателем');await teacher.locator('#grade').click();await expect(teacher.locator('#historyList')).toContainText('Проверено преподавателем');await expect(teacher.locator('#assessmentDetail')).toContainText('85%');
 await teacher.locator('#expertReason').fill('Отзыв после повторной проверки');await teacher.locator('#revoke').click();await expect(teacher.locator('#dialogStatus')).toContainText('уже изменено');await expect(teacher.locator('#expertReason')).toHaveValue('Отзыв после повторной проверки');await teacher.locator('#revoke').click();await expect(teacher.locator('#historyList')).toContainText('Оценка отозвана');await expect(teacher.locator('#historyList .card')).toHaveCount(2);await expect(teacher.locator('#assessmentDetail')).toContainText('источник: Автоматически');
 role='student';const student=await browser.newPage({viewport:{width:1200,height:800}});student.on('pageerror',e=>errors.push(e.message));await serve(student);await student.goto(origin+'/assessment');await expect(student.locator('#pageTitle')).toHaveText('Мои результаты');await expect(student.locator('#teacherPolicy')).toBeHidden();await expect(student.locator('#groupWrap')).toBeHidden();await expect(student.locator('#studentsSection')).toBeHidden();await expect(student.locator('#groupInsights')).toBeHidden();await expect(student.locator('#progress')).toContainText('Учебное задымление');await student.locator('#progress tr[data-session]').click();await expect(student.locator('#expertForm')).toBeHidden();await expect(student.locator('#assessmentDetail')).toContainText('Автоматическая диагностика');
 const studentInstructorCalls=calls.filter(x=>x.startsWith('student:')&&x.includes('/instructor/'));if(studentInstructorCalls.length)throw Error('Student UI requested teacher data: '+studentInstructorCalls.join(','));await teacher.setViewportSize({width:400,height:900});const overflow=await teacher.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);if(overflow>1)throw Error('Horizontal overflow at 400px: '+overflow);
 if(errors.length)throw Error(errors.join('\n'));console.log('Assessment browser flow: PASS (mock HTTP, teacher policy/expert audit and private student stats)');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
