mark('112 AI Trainer · учебный цикл диспетчера ДДС');
await page.waitForTimeout(4000);
mark('Библиотека · 32 билета и 96 упражнений');
await page.getByRole('link',{name:'Учебные билеты',exact:true}).click();
await page.waitForTimeout(4500);
await page.screenshot({path:'/capture/overview-tickets.png'});
mark('Сценарии · исходная карточка, бригада и доклады');
await page.goto(base+'/scenarios');
const id=JSON.parse(require('fs').readFileSync('/capture/demo-scenario.json','utf8')).id;
await page.locator('#selected').selectOption(id);
await page.locator('#status').filter({hasText:'Сценарий загружен'}).waitFor();
await page.getByRole('heading',{name:'Готовая карточка для ДДС',exact:true}).scrollIntoViewIfNeeded();
await page.waitForTimeout(4500);
mark('Материалы · справочная база обучения');
await page.goto(base+'/materials');
await page.waitForTimeout(4500);
mark('Оценивание · решения, ошибки и прогресс');
await page.goto(base+'/assessment');
await page.waitForTimeout(5000);
await shot();
return await end();
