const fs=require('fs'),title='Демонстрация ДДС · 28 сентября';
await page.goto(base+'/portal');
await page.locator('#groupTitle').waitFor();
mark('Группа и участники');
await page.locator('#groupTitle').fill('Учебная группа · видео 28.09');
await page.locator('#groupForm button').click();
const group=page.locator('#groups article').filter({has:page.getByRole('heading',{name:'Учебная группа · видео 28.09',exact:true})});
await group.getByLabel('Студент').selectOption({label:await group.locator('option').filter({hasText:'(kursant1)'}).textContent()});
await group.getByRole('button',{name:'Добавить',exact:true}).click();
await page.locator('#status').filter({hasText:'Студент добавлен'}).waitFor();
await page.waitForTimeout(2500);
mark('Назначение сценария и SIP-номера');
await page.locator('#lessonTitle').fill(title);
await page.locator('#lessonGroup').selectOption({label:'Учебная группа · видео 28.09'});
await page.locator('#lessonMode').selectOption('actions');
await page.locator('#lessonTransport').selectOption('sip');
await page.locator('#lessonExtensions input').fill('220');
await page.locator('#lessonGenerated').selectOption(JSON.parse(fs.readFileSync('/capture/demo-scenario.json','utf8')).id);
await page.locator('#lessonCount').fill('1');
await page.locator('#lessonPlaces input').fill('АРМ-1');
await page.locator('#lessonForm').getByRole('button',{name:'Подготовить занятие'}).click();
await page.locator('#status').filter({hasText:'Занятие подготовлено'}).waitFor();
await page.waitForTimeout(2500);
mark('Запуск и наблюдение за занятием');
const lesson=page.locator('#lessons article').filter({has:page.getByRole('heading',{name:title,exact:true})});
await lesson.getByRole('button',{name:'Начать',exact:true}).click();
await lesson.getByRole('button',{name:'Участники в реальном времени'}).click();
await page.waitForTimeout(2500);
return await shot();
