const fs=require('fs');
mark('Вход в занятие преподавателя');
await page.getByRole('link',{name:'Перейти в рабочее место',exact:true}).click();
await page.locator('#activeLesson option').filter({hasText:'Демонстрация ДДС · 28 сентября'}).waitFor({state:'attached'});
const lessonId=await page.locator('#activeLesson option').filter({hasText:'Демонстрация ДДС · 28 сентября'}).getAttribute('value');
await page.locator('#activeLesson').selectOption(lessonId);
const waiting=page.waitForResponse(r=>r.url().includes('/student/lessons/'+lessonId+'/next')&&r.ok(),{timeout:20000});
await page.locator('#joinLesson').click();
const received=await waiting;
const session=await received.json();
fs.writeFileSync('/capture/session.json',JSON.stringify({session_id:session.id,lesson_id:lessonId,card:session.card}));
mark('Входящая карточка и приём за 30 секунд');
await page.getByRole('button',{name:'Открыть карточку '+session.number,exact:true}).click();
await page.locator('.service-tile.own-service .service-edit').click();
await page.locator('#responseStatus').selectOption({label:'Принята'});
await page.locator('#addResponse').click();
await page.waitForTimeout(1500);
mark('Назначение реагирующей бригады');
await page.locator('#assignCrew').click();
await page.waitForTimeout(1500);
return await shot();
