const fs=require('fs');
const scenario=JSON.parse(fs.readFileSync('/capture/scenario.json','utf8'));
mark('Создание учебного сценария');
await page.getByRole('link',{name:'Сценарии',exact:true}).click();
await page.locator('#selected').selectOption(scenario.id);
await page.locator('#status').filter({hasText:'Сценарий загружен'}).waitFor();
await page.waitForTimeout(2500);
await page.locator('#copy').click();
await page.locator('[data-key=title]').fill('ДДС · помощь ребёнку после падения');
await page.locator('[data-key=description]').fill('Получить карточку, организовать выезд медицинской бригады, принять доклады и зафиксировать результат.');
await page.locator('[data-key=title]').scrollIntoViewIfNeeded();
await page.waitForTimeout(2500);
mark('Настройка бригады и оперативных докладов');
await page.getByRole('heading',{name:'Оперативные доклады',exact:true}).scrollIntoViewIfNeeded();
await page.waitForTimeout(3500);
await page.locator('#save').click();
await page.locator('#status').filter({hasText:'Сценарий сохранён'}).waitFor();
const id=await page.locator('[data-key=id]').inputValue();
fs.writeFileSync('/capture/demo-scenario.json',JSON.stringify({id}));
await page.waitForTimeout(2500);
return await shot();
